export const localized = {
  addAgents: /Add agents to your org|添加智能体/i,
  boardChatPlaceholder: /Ask anything about your company|询问任何关于你公司的问题/i,
  buildNewTeam: /Build a new (?:team|company)|组建团队/i,
  chiefOfStaffPlaceholder: /Chief of staff|幕僚长/i,
  confirmMission: /Confirm mission|确认使命/i,
  defineMission: /Define your mission|定义你的使命/i,
  getStarted: /Get started|开始使用/i,
  giveItAHeartbeat: /Give it a heartbeat|给它一次心跳/i,
  inReviewStatusButton: /^(In Review|In review|审核中)(\s+(In Review|In review|审核中))*$/i,
  missionPlaceholder: /What is your team trying to achieve\?|你的团队想实现什么？/i,
  nameYourTeam: /Name your (?:team|company)|命名你的团队|命名你的公司|为你的公司命名/i,
  next: /^(Next|下一步)/i,
  planMode: /Plan mode|规划模式/i,
  review: /^(Review|审阅)$/i,
  startOnboarding: /Start Onboarding|New Company|Add Agent|开始引导|新建公司|添加智能体/i,
  tellUsAboutTeam: /Tell us about your team|告诉我们你的团队/i,
  welcome: /Welcome to Paperclip(?: CN)?|欢迎使用 Paperclip CN/i,
};
