export const localized = {
  addAgents: /Add agents to your org|添加智能体/i,
  appAccessEnabled: /Agents can use this app|智能体.*可以使用此应用/i,
  appAdvancedSetup: /^(Advanced setup|高级设置)$/i,
  appAskFirst: /^(Ask first|先询问|先问)$/i,
  appBrowse: /^(Browse|浏览)$/i,
  appCanMakeChanges: /^(Can make changes|可更改|可以做出改变)$/i,
  appCheckLink: /Check link|检查链接/i,
  appConnect: /^(Connect|连接)$/i,
  appConnectOwnTool: /Connect your own tool|连接你自己的工具/i,
  appConnectTitle: /^(Connect an app|连接应用)$/i,
  appConnectWithLink: /Connect with a link|通过链接连接/i,
  appConnectedSummary: /Connected to .* it offers|已连接到 .*提供/i,
  appConnections: /^(Connections|连接)$/i,
  appContinueActions: /Continue with .* actions? on|继续启用 .* 个操作/i,
  appContinueInstall: /Continue to install|继续安装/i,
  appDangerZone: /^(Danger zone|危险区域)$/i,
  appFinishSetup: /Finish setup|完成设置/i,
  appInstallTools: /Install .* tools\?|要安装 .* 的工具吗？/i,
  appIsolatedWorkspace: /isolated workspace|隔离工作区/i,
  appName: /^(App name|应用名称)$/i,
  appNeedsAttention: /needs attention|需要处理|需要注意|需关注/i,
  appNotConnected: /^(Not connected|未连接)$/i,
  appOpenOrReview: /Open|Review|打开|审阅/i,
  appPasteConfig: /Paste a config|粘贴配置|粘贴一个配置/i,
  appPause: /Pause this app|暂停此应用/i,
  appPaused: /This app is paused|该应用已暂停/i,
  appPreviousSetup: /Previous setup|之前的设置/i,
  appReadOnly: /^(Read only|只读)$/i,
  appReconnect: /^(Reconnect|重新连接)$/i,
  appReconnectOrReplaceKey: /Reconnect|Replace key|重新连接|替换密钥/i,
  appReconnectTitle: /Reconnect this app|重新连接此应用/i,
  appRemove: /^(Remove app|删除应用)$/i,
  appRemoveConfirm: /Yes, remove it|是的，删除它/i,
  appRemoved: /App removed|应用已删除/i,
  appRename: /Rename app|重命名应用/i,
  appResume: /Resume this app|恢复此应用/i,
  appRunOwn: /Run your own|Self host|Stdio|Local|自己运行|运行你自己的|自托管|本地/i,
  appSuccess: /ready|all set|done|已就绪|全部设置|完成/i,
  appWhoCanUse: /Who can use|谁可以使用/i,
  apps: /^(Apps|应用)$/i,
  boardChatPlaceholder: /Ask anything about your company|询问任何关于你公司的问题/i,
  buildNewTeam: /Build a new (?:team|company)|组建团队/i,
  chiefOfStaffPlaceholder: /Chief of staff|幕僚长/i,
  commonContinue: /^(Continue|继续)$/i,
  commonSave: /^(Save|保存)$/i,
  confirmMission: /Confirm mission|确认使命/i,
  defineMission: /Define your mission|定义你的使命/i,
  developerTools: /^(Developer tools|开发者工具)$/i,
  getStarted: /Get started|开始使用/i,
  giveItAHeartbeat: /Give it a heartbeat|给它一次心跳/i,
  inReviewStatusButton: /^(In Review|In review|审核中)(\s+(In Review|In review|审核中))*$/i,
  missionPlaceholder: /What is your team trying to achieve\?|你的团队想实现什么？/i,
  nameYourTeam: /Name your (?:team|company)|命名你的团队|命名你的公司|为你的公司命名/i,
  next: /^(Next|下一步)/i,
  planMode: /Plan mode|规划模式/i,
  recentActivity: /^(Recent activity|Recent Activity|最近活动|最近的活动)$/i,
  review: /^(Review|审阅)$/i,
  reviewQueueEmpty: /Nothing is waiting for your OK|new actions? (need|to) review|目前没有任何待你批准的事项|需要审查的新行动|待审查的新操作/i,
  startOnboarding: /Start Onboarding|New Company|Add Agent|开始引导|新建公司|添加智能体/i,
  tellUsAboutTeam: /Tell us about your team|告诉我们你的团队/i,
  toolsAccessProfiles: /^(Access profiles|访问配置)$/i,
  toolsPasteDescription: /Paste the MCP config snippet|粘贴.*MCP 配置片段/i,
  welcome: /Welcome to Paperclip(?: CN)?|欢迎使用 Paperclip CN/i,
};
